define([
    'bootstrapping/knockoutBindings/areaBinding',
    'bootstrapping/knockoutBindings/autofocusBinding',
    'bootstrapping/knockoutBindings/autosizeBinding',
    'bootstrapping/knockoutBindings/backgroundBinding',
    'bootstrapping/knockoutBindings/circleProgressBinding',
    'bootstrapping/knockoutBindings/contextBinding',
    'bootstrapping/knockoutBindings/elementsWrapBinding',
    'bootstrapping/knockoutBindings/focusHandlerBinding',
    'bootstrapping/knockoutBindings/toggleVisibleBindingHandler',
    'bootstrapping/knockoutBindings/dropDownBinding',
    'bootstrapping/knockoutBindings/scrollTopBinding',
    'bootstrapping/knockoutBindings/scrollIntoViewBinding',
    'bootstrapping/knockoutBindings/learningContentBinding',
    'bootstrapping/knockoutBindings/toolTipBindingHandler',
    'bootstrapping/knockoutBindings/downloadAsPdfBinding',
    'bootstrapping/knockoutBindings/mediaPlayerBinding',
    'bootstrapping/knockoutBindings/customFocusBinding',
    'bootstrapping/knockoutBindings/reviewableBinding',
    'bootstrapping/knockoutBindings/limitedLengthTextBinding',
    'bootstrapping/knockoutBindings/scrollbarBinding',
    'bootstrapping/knockoutBindings/localizeBinding',
    'bootstrapping/knockoutBindings/fontScaleBinding',
    'treeOfContent/bindingHandlers/treeOfContentAnimationsBinding',
    'bootstrapping/knockoutBindings/selectTextBinding',
    'bootstrapping/knockoutBindings/submitOnEnterBinding',
    'bootstrapping/knockoutBindings/keyDownBinding',
    'bootstrapping/knockoutBindings/tabFocusBinding',
    'bootstrapping/knockoutBindings/copyToClipboardBinding',
    'bootstrapping/knockoutBindings/changeCssClassByDelayBinding',
    'bootstrapping/knockoutBindings/containImageBinding',
    'viewmodels/questions/dragAndDrop/bindingHandlers/draggableTextBindingHandler',
    'viewmodels/questions/dragAndDrop/bindingHandlers/draggableTextContainerBindingHandler',
    'viewmodels/questions/dragAndDrop/bindingHandlers/dropspotBindingHandler',
    'viewmodels/questions/fillInTheBlank/bindingHandlers/fillInTheBlankAnswersBinding',
    'viewmodels/questions/textMatching/bindingHandlers/draggableBindingHandler',
    'viewmodels/questions/textMatching/bindingHandlers/droppableBindingHandler',
    'viewmodels/questions/textMatching/bindingHandlers/overlayBindingHandler',
    'viewmodels/questions/textMatching/bindingHandlers/syncHeightBindingHandler',
    'viewmodels/questions/openQuestion/bindingHandlers/textAreaBindingHandler',
    'viewmodels/questions/singleSelectImage/bindingHandlers/previewImageBinding',
    'widgets/imagePreview/bindingHandlers/fadeBindingHandler',
    'widgets/imagePreview/bindingHandlers/imageLoaderBindingHandler',
    'dialogs/bindingHandlers/blockBodyScrollBinding'
], function () {

    return {
        execute: function () { }
    };

});